### ISSUE TITLE
Broken link to Developing Cloudflow streamlets

### ISSUE THREAD

**Issue by beritou** [lightbend/cloudflow-docs#21]
[Here](https://cloudflow.io/docs/current/concepts.html#_where_to_go_next) there is a link to ```Developing Cloudflow streamlets``` https://cloudflow.io/docs/current/concepts.html#develop:cloudflow-streamlets.adoc. When clicked, nothing happens.

Normally I would submit a PR myself for this kind of thing, but the doc link generation has some complexity that I wasn't able to quickly grok.

Possibly related to #13

**Comment by rstento** [comment]
@beritou, thanks for reporting! We've removed the concepts page, so this s/be resolved.
